AllCops:
  EnabledByDefault: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Copyright:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineHashKeyLineBreaks:
  Enabled: false

Layout/FirstMethodParameterLineBreak:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false
